---
- name: "Podman | {{ ansible_os_family }} | Installing Podman packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - podman
    - buildah
    - skopeo

- name: "Podman | {{ ansible_os_family }} | Installing Cockpit package"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - cockpit
    - cockpit-podman
  when: 
    - PODMAN_SYSTEMD_INSTALL_COCKPIT is defined
    - PODMAN_SYSTEMD_INSTALL_COCKPIT