---
- name: "Podman | {{ pm_user }} | Rootless | Create configuration directory"
  ansible.builtin.file:
    path: $HOME/.config/containers/
    state: directory
    mode: '0750'
    # recurse: yes
  become_user: "{{ pm_user }}"
